import type { Metadata } from "next";
import { Geist, Geist_Mono, Noto_Sans_Ethiopic} from "next/font/google";
import "./globals.css";
import Navbar from '../components/navbar'
import Footer from '../components/footer'
import { ThemeProvider } from "@/lib/theme-provider"


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const notoSansEthiopic = Noto_Sans_Ethiopic({
  variable: "--font-noto-sans-ethiopic",
  subsets: ["ethiopic"],
});

export const metadata: Metadata = {
  title: "ገበያ - E-commerce Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`flex min-h-full flex-col bg-background text-foreground ${geistSans.variable} ${geistMono.variable} ${notoSansEthiopic.variable}`}
      >
        <ThemeProvider
          defaultTheme="system"
          storageKey="ui-theme"
        >
          <div className="flex flex-col min-h-screen">
            <Navbar />
            <main className="grow container mx-auto px-4 py-8">
              {children}
            </main>
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
